### ISSUE TITLE
lipd_read appears to load as a list instead of a lipd

### ISSUE THREAD

**Issue by cknightgov** [nickmckay/lipdR#16]
Hello! I have been using geoChronR to analyze lipd files. Last week I was able to upload lipd files and they would appear in my R environment as "Large lipd (11 elements, 1.1 MB)", for example. Reloading the same lipd file now produces "List of 11" in my R environment. This is having knock-on effects with not being able to produce an age ensemble after running a model (e.g. runBacon()). 

Hopefully I am asking this question in the right venue/way. Thank you for your time.

**Comment by nickmckay** [comment]
Hmm,

That's interesting. It should still be loading in as a lipd object,
although that's also a list so it might show up that way in the
environment. What do you get if you run `class(L)` where L is the loaded
object?

Also, geoChronR (and `runBacon()`) should still work, even if it's a list.
What error are you getting there? Are you getting similar errors with other
files, or just this one?

**Comment by cknightgov** [comment]
I get [1] "lipd" "list" when I ask for the class of the object. 

RunBacon(L) works and produces the ghost plots etc, but when I try to plot it using plotChron(L), I get the error that there is no age ensemble. Using View(L), I can indeed see that there is no ensemble table or model, unlike previous runs where that info is clearly in the "chronData" section.

I reuploaded another file to check (the Hudson.Clegg.2011 dataset from the vignette) and this is also occurring with that file: I get a "list" in the R environment, I can runBacon(), but when I try plotting using plotChron() there is no model/age ensemble so it simply plots the calibrated ages against depth.

Lastly, is there a way to use my 210Pb data and associated error with this software, as in call Plum() instead of just Bacon()? Or some kind of work-around to use 210Pb with 14C? 

Thank you so much!

**Comment by nickmckay** [comment]
OK,

The fact that you get "lipd" as one of the classes is a good sign.

When you run `runBacon()`, if it makes it through without errors, then it
should be storing the ensembles. Are you overwriting L in that call? *e.g.
`L = runBacon(L)` or are you storing that elsewhere? Only the output
updated lipd object should have the ensemble.

Lastly, Plum is not yet implemented in geoChronR, so it doesn't know how to
extract the ensembles (it's on the to do list!). There are a few
alternative strategies here we've used before, but the simplest is to
include some of the output of the 210Pb model in the Bacon run.

**Comment by cknightgov** [comment]
Ok that's good! 

Actually runBacon() does create an error, I had missed it previously:
Error in tcrossprod(x, y) : 
  requires numeric/complex matrix/vector arguments

I tried L = runBacon(L) and L2 = runBacon(L) and got the same error message about the tcrossprod(x, y). 

Thanks for clarifying about Plum and for providing a work-around for the time being!

**Comment by nickmckay** [comment]
OK, I'm going to close this and move it to geoChronR: https://github.com/nickmckay/GeoChronR/issues/79
