### ISSUE TITLE
writeLipd() no longer automatically writes/names files after currently loaded .lpd dataset name

### ISSUE THREAD

**Issue by AndreaLemur** [nickmckay/lipdR#9]
I'm not sure if this is a bug, but it was a useful feature in my workflow that now seems to be missing.

writeLipd() no longer automatically writes and names files after the currently loaded dataset when selecting any differently named file in a given folder. That is, if I want to save a newly generated age ensemble to A.lpd, I used to be able to run writeLipd() interactively and click on any other file in a given folder (e.g., B.lpd) and a copy of A.lpd with the age ensemble would be saved to that folder without any further prompting. Now when I do this, writeLipd() runs interactively, but if I click on B.lpd and hit the "save" button, I am prompted to overwrite B.lpd with A.lpd with "Yes", "No", and "Cancel" options.

When choosing cancel, writeLipd() returns the following error: `Error: writeLipd: Error in if (!ans) {: missing value where TRUE/FALSE needed`

When trying to rerun writeLipd() in the same session, it returns the following error: `Error: writeLipd: Error in doTryCatch(return(expr), name, parentenv, handler): The input object should be of class lipd or multiLipd`

**Comment by AndreaLemur** [comment]
After manually naming the file I'm trying to save using writeLipd(), I get the following errors:

`writing: F-14.Dianchi.Hillman.2021 to C:\\Users\\andil\\Desktop\\Thesis\\LiPD Files with AgeEnsembles\\F-14.Dianchi.Hillman.2021.lpd`
`Warning: bagit: There was an error while prepping for Bagit: \n Continuing to write LiPD file without bagging Error in get(\"bagit.script\", lipdEnv): object 'bagit.script' not found\n`
`Zipping failed: Error in doTryCatch(return(expr), name, parentenv, handler): zip file not created\n`

It seems like the new file wasn't even created.

For reference, I am using lipdR version 0.3.5 in R version 4.1.3.

Edit: In R 4.2.1, I do not get the 'Zipping failed' error.

**Comment by nickmckay** [comment]
Thanks for this. This was an intentional change, as 0.3.5 allows the user to now name files with something other than the dataSetName, meaning that that old workflow no longer made sense. I'll consider options for how to replace the old workflow, which I also used frequently. The second post seems like a bug, and I'll look into that too. If you type the path into `writeLipd()` does it work as expected?

**Comment by AndreaLemur** [comment]
Hi Nick, yes, typing the path into `writeLipd()` works as expected.
